# Generated by Django 4.1.7 on 2023-03-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('country', models.CharField(default='kenya', max_length=100)),
                ('city', models.CharField(default='nairobi', max_length=100)),
            ],
        ),
    ]
